#!/usr/bin/env python3
"""
Research and Report Generator

This script automates the process of researching topics through web search
and authoritative sources, then synthesizes findings into structured reports.

Usage:
    Modify the parameters in the main() function below, then run:
    python research_and_report.py
"""

import asyncio
import sys
import os
from datetime import datetime
from typing import List, Optional

# Add the extensions directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../..'))

from extensions.wrapped_mcp.mcp_server_search import web_search
from extensions.wrapped_mcp.mcp_server_fetch import fetch


async def research_and_generate_report(
    topic: str,
    output_path: str,
    num_search_results: int = 5,
    official_urls: Optional[List[str]] = None,
    max_fetch_length: int = 10000
) -> dict:
    """
    Execute a complete research and reporting workflow.
    
    Args:
        topic: The research topic/query
        output_path: Where to save the final report
        num_search_results: Number of web search results to gather
        official_urls: List of authoritative URLs to fetch content from
        max_fetch_length: Maximum characters to fetch from each URL
    
    Returns:
        dict with keys: success (bool), report_path (str), file_size (int), error (str)
    """
    print(f"🔍 Starting research on: {topic}\n")
    
    results = {
        "success": False,
        "report_path": output_path,
        "file_size": 0,
        "error": None
    }
    
    # Step 1: Web Search
    print(f"📡 Executing web search (requesting {num_search_results} results)...")
    try:
        search_results = await web_search({
            "query": topic,
            "num_results": num_search_results
        })
        print("✅ Web search completed\n")
    except Exception as e:
        error_msg = f"Web search failed: {e}"
        print(f"❌ {error_msg}\n")
        results["error"] = error_msg
        return results
    
    # Step 2: Fetch Official Sources
    fetched_content = []
    if official_urls:
        print(f"📄 Fetching content from {len(official_urls)} authoritative source(s)...")
        for url in official_urls:
            try:
                print(f"  - Fetching: {url}")
                content = await fetch({
                    "url": url,
                    "max_length": max_fetch_length
                })
                fetched_content.append({
                    "url": url,
                    "content": content
                })
                print(f"    ✅ Retrieved {len(content)} characters")
            except Exception as e:
                print(f"    ⚠️ Error: {e}")
                fetched_content.append({
                    "url": url,
                    "content": f"Error fetching content: {e}"
                })
        print()
    
    # Step 3: Synthesize Report
    print("📝 Synthesizing report...")
    
    report = f"""# {topic} - Research Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 🔍 Web Search Results

{search_results}

"""
    
    # Add fetched content section if available
    if fetched_content:
        report += "\n## 📚 Authoritative Sources\n\n"
        for item in fetched_content:
            report += f"### Source: {item['url']}\n\n"
            report += f"{item['content']}\n\n"
            report += "---\n\n"
    
    # Add synthesis section
    report += """## 💡 Key Insights

This report compiles information from multiple sources including web search results"""
    
    if fetched_content:
        report += f" and {len(fetched_content)} authoritative source(s)"
    
    report += """.

**Research Methodology:**
- Web search engine: DuckDuckGo
- Number of search results: """ + str(num_search_results) + """
"""
    
    if official_urls:
        report += f"- Official sources consulted: {len(official_urls)}\n"
    
    report += f"""
**Total Information Gathered:**
- Search results: {len(search_results)} characters
"""
    
    if fetched_content:
        total_fetched = sum(len(item['content']) for item in fetched_content)
        report += f"- Fetched content: {total_fetched} characters\n"
    
    report += f"\n---\n\n*Report generated by Research Reporter skill*\n"
    
    # Step 4: Save to File
    print(f"💾 Saving report to: {output_path}")
    try:
        # Ensure directory exists
        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report)
        
        file_size = len(report)
        print(f"✅ Report saved successfully!")
        print(f"📊 File size: {file_size:,} characters\n")
        
        results["success"] = True
        results["file_size"] = file_size
        
    except Exception as e:
        error_msg = f"Failed to save report: {e}"
        print(f"❌ {error_msg}\n")
        results["error"] = error_msg
        return results
    
    return results


async def main():
    """
    Main function - Customize these parameters for your research needs.
    """
    
    # ========== CUSTOMIZE THESE PARAMETERS ==========
    
    # What to research
    TOPIC = "TypeScript 2024 2025 latest trends new features"
    
    # Where to save the report
    OUTPUT_PATH = "/tmp/research_report.txt"
    
    # Number of web search results to gather
    NUM_SEARCH_RESULTS = 5
    
    # Optional: List of authoritative URLs to fetch
    OFFICIAL_URLS = [
        "https://www.typescriptlang.org/",
    ]
    
    # Maximum characters to fetch from each URL
    MAX_FETCH_LENGTH = 10000
    
    # ================================================
    
    results = await research_and_generate_report(
        topic=TOPIC,
        output_path=OUTPUT_PATH,
        num_search_results=NUM_SEARCH_RESULTS,
        official_urls=OFFICIAL_URLS,
        max_fetch_length=MAX_FETCH_LENGTH
    )
    
    if results["success"]:
        print("=" * 60)
        print("✅ RESEARCH COMPLETED SUCCESSFULLY")
        print("=" * 60)
        print(f"📁 Report Location: {results['report_path']}")
        print(f"📊 Report Size: {results['file_size']:,} characters")
        print("=" * 60)
    else:
        print("=" * 60)
        print("❌ RESEARCH FAILED")
        print("=" * 60)
        print(f"Error: {results['error']}")
        print("=" * 60)
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
